### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by groovecoder** [codefortulsa/tulsa-county-inmate-information-center-api#11]
Is it as easy as adding a `Procfile` with `node server.js` and pushing to Heroku?

**Comment by pipakin** [comment]
Probably? I'm a complete and utter heroku noob. You'll probably want a custom .iic-apirc file with whitelisted urls and a different port unless you want to access it from localhost at 3030.

**Comment by pipakin** [comment]
*whitelisted ips.

**Comment by pipakin** [comment]
Looks like an appropriate Procfile and a minor change to package.json and we'd be good to go.  I'll give it a shot later once I have a few minutes and then get it checked in.
